apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-reactapp-client
spec:
  selector:
    matchLabels:
      app: jobportal-reactapp-client
  replicas: 1
  template:
    metadata:
      labels:
        app: jobportal-reactapp-client
    spec:
      containers:
        - name: jobportal-reactapp-client
          image: pankajdets/reactkuberimg
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jobportal-reactapp-client-service
spec:
  selector:
    app: jobportal-reactapp-client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer
